//To use this script, put this into the pipeline:
//    parameters {
//        booleanParam(name: 'SLACK_NOTIFICATION', defaultValue: 'True', description: 'Send an Slack Notification?')
//        string(name: 'email_recipients', defaultValue: '', description: 'If you wish to send an email notification, write there the receiver.')
//    }
//And this is how the call function should looks like: sendNotification(Variable_comment, params.email_recipients)
// buildStatus should be automaticly generated by the script

def call(String comment = '', String email_recipients = '', String buildStatus = 'STARTED') {
    //Build status of null means success.
    buildStatus = buildStatus ?: 'SUCCESS'
    
    echo comment
    echo email_recipients
    echo buildStatus
    
    def color
    if (buildStatus == 'STARTED') {
        color = '#87CEFA'
    } else if (buildStatus == 'SUCCESS') {
        color = '#BDFFC3'
    } else if (buildStatus == 'UNSTABLE') {
        color = '#FFFE89'
    } else {
        color = '#FF9FA1'
    }

    def msg = "${buildStatus}: `${env.JOB_NAME}` #${env.BUILD_NUMBER}:\n${env.BUILD_URL}\n${comment}"
    
    if (params.SLACK_NOTIFICATION == true) {
        //slackSend(color: color, message: msg)
        echo "notify slack works"
    }
    if (email_recipients != '') {
        notifyMail(email_recipients, msg)
    }
}
